import { VoluntaryModelB, VoluntaryStatus } from './voluntary.model';
import { Injectable } from '@nestjs/common';
import * as uuid from 'uuid';

@Injectable()
export class AppService {
  VOLUNTEERS: VoluntaryModelB[] = [
    {
      id: 1,
      nome: 'Adriana da Silva Meluieer Bragança',
      sexo: 'Feminino',
      dataNascimento: '1995-06-19',
      profissao: 'estudante',
      cepVo: '23092-002',
      logradouroVo: 'Rua da pedras cinzentas',
      numeroVo: '897',
      bairroVo: 'MeuBairro897',
      cidadeVo: 'Rio de Janeiro',
      ufVo: 'RJ',
      complementoVo: 'RJ',
      CEPVo: 'RJ',
      instituicao: 'Igreja',
      nomeIg: 'Primeira Igreja Batista em Torinho Branco',
      telefoneIg: '(21) 4358-9621',
      cepIg: '23093-002',
      logradouroIg: 'Rua da pedras brilhantes',
      numeroIg: '898',
      bairroIg: '898',
      cidadeIg: 'Rio de Janeiro',
      complementoIg: 'Rio de Janeiro',
      ufIg: 'RJ',
      pastor: 'João Batista de Jesus',
      telefonePa: '(21) 98563-1045',
      cepPa: '23094-002',
      logradouroPa: 'Rua da pedras amarelas',
      numeroPa: '899',
      cidadePa: 'Rio de Janeiro',
      bairroPa: 'Rio de Janeiro',
      complementoPa: 'Rio de Janeiro',
      ufPa: 'RJ',
      servicoOferecido: 'disicpulador',
      disponibilidade: 'Aos sábados',
      assiduidade: 'Aos sábados',
      diponivel: true,
      outrasInformacoes:
        'setá disponivel para participar do congresso radical, pretende fazer parte do programa de vontariado',
      email: 'dikaSilva@gmail.com',
      telefoneVo: '(21) 986589970',
      imgUrl: './assets/volu2.jpeg',
      dataCad: null,
      status: VoluntaryStatus.ACTIVE,
    },
    {
      id: 4,
      nome: 'Bruna Medeiros ',
      sexo: 'F',
      dataNascimento: '1995-06-21',
      profissao: 'cabelereira',
      cepVo: '21458965',
      logradouroVo: 'Rua Novo Oeste',
      numeroVo: '2823',
      bairroVo: 'MeuBairro2823',
      cidadeVo: 'São Paulo',
      ufVo: 'SP',
      complementoVo: 'SP',
      CEPVo: 'SP',
      instituicao: 'Igreja',
      nomeIg: 'Primeira Igreja Batista em SP',
      telefoneIg: '(11) 25698741',
      cepIg: '45632987',
      logradouroIg: 'Rua Pedra Bela',
      numeroIg: '1145',
      bairroIg: '1145',
      cidadeIg: 'São Paulo',
      complementoIg: 'São Paulo',
      ufIg: 'SP',
      pastor: 'MArco Aurélio Silva',
      telefonePa: '(11) 985632589',
      cepPa: '45638574',
      logradouroPa: 'Avenida do Estado',
      numeroPa: '1200',
      cidadePa: 'São Paulo',
      bairroPa: 'São Paulo',
      complementoPa: 'São Paulo',
      ufPa: 'SP',
      servicoOferecido: 'Cabelereira',
      disponibilidade: 'Aos segundas',
      assiduidade: 'umaVezPorSemana',
      diponivel: true,
      outrasInformacoes:
        'setá disponivel para participar do congresso radical, pretende fazer parte do programa de vontariado',
      email: 'brunamedeiros@gmail.com',
      telefoneVo: '(11) 965874521',
      imgUrl: './assets/volu4.jpeg',
      dataCad: null,
      status: VoluntaryStatus.ACTIVE,
    },
    {
      id: 5,
      nome: 'Alessandro Vieira Fernandes ',
      sexo: 'Masculino',
      dataNascimento: '1995-06-19',
      profissao: 'estudante',
      cepVo: '23092-002',
      logradouroVo: 'Rua da pedras cinzentas',
      telefoneVo: '(21) 986589970',
      numeroVo: '897',
      bairroVo: 'MeuBairro897',
      cidadeVo: 'Rio de Janeiro',
      ufVo: 'RJ',
      complementoVo: 'RJ',
      CEPVo: '21865355',
      instituicao: 'Igreja',
      nomeIg: 'Primeira Igreja Batista em Torinho Branco',
      telefoneIg: '(21) 4358-9621',
      cepIg: '23093-002',
      logradouroIg: 'Rua da pedras brilhantes',
      numeroIg: '898',
      bairroIg: '898',
      cidadeIg: 'Rio de Janeiro',
      complementoIg: 'Rio de Janeiro',
      ufIg: 'RJ',
      pastor: 'João Batista de Jesus',
      telefonePa: '(21) 98563-1045',
      cepPa: '23094-002',
      logradouroPa: 'Rua da pedras amarelas',
      numeroPa: '899',
      cidadePa: 'Rio de Janeiro',
      bairroPa: 'Rio de Janeiro',
      complementoPa: 'Rio de Janeiro',
      ufPa: 'RJ',
      servicoOferecido: 'disicpulador',
      disponibilidade: 'Aos sábados',
      assiduidade: 'Aos sábados',
      diponivel: true,
      outrasInformacoes:
        'setá disponivel para participar do congresso radical, pretende fazer parte do programa de vontariado',
      email: 'dikaSilva@gmail.com',
      imgUrl: './assets/volu3.jpeg',
      dataCad: 'seg,25 de mai, 2020',
      status: VoluntaryStatus.ACTIVE,
    },
    {
      id: 6,
      nome: 'Sônia Gonsalves da Silva ',
      sexo: 'Feminino',
      dataNascimento: '1995-06-19',
      profissao: 'estudante',
      cepVo: '23092-002',
      logradouroVo: 'Rua da pedras cinzentas',
      telefoneVo: '(21) 986589970',
      numeroVo: '897',
      bairroVo: 'MeuBairro897',
      cidadeVo: 'Rio de Janeiro',
      ufVo: 'RJ',
      complementoVo: 'RJ',
      CEPVo: 'RJ',
      instituicao: 'Igreja',
      nomeIg: 'Primeira Igreja Batista em Torinho Branco',
      telefoneIg: '(21) 4358-9621',
      cepIg: '23093-002',
      logradouroIg: 'Rua da pedras brilhantes',
      numeroIg: '898',
      bairroIg: '898',
      cidadeIg: 'Rio de Janeiro',
      complementoIg: 'Rio de Janeiro',
      ufIg: 'RJ',
      pastor: 'João Batista de Jesus',
      telefonePa: '(21) 98563-1045',
      cepPa: '23094-002',
      logradouroPa: 'Rua da pedras amarelas',
      numeroPa: '899',
      cidadePa: 'Rio de Janeiro',
      bairroPa: 'Rio de Janeiro',
      complementoPa: 'Rio de Janeiro',
      ufPa: 'RJ',
      servicoOferecido: 'disicpulador',
      disponibilidade: 'Aos sábados',
      assiduidade: 'Aos sábados',
      diponivel: true,
      outrasInformacoes:
        'setá disponivel para participar do congresso radical, pretende fazer parte do programa de vontariado',
      email: 'dikaSilva@gmail.com',
      imgUrl: './assets/volu6.jpeg',
      dataCad: 'seg,25 de mai, 2020',
      status: VoluntaryStatus.ACTIVE,
    },
    {
      id: 7,
      nome: 'Thayse Alvez Romanu ',
      sexo: 'Feminino',
      dataNascimento: '1995-06-19',
      profissao: 'estudante',
      cepVo: '23092-002',
      logradouroVo: 'Rua da pedras cinzentas',
      telefoneVo: '(21) 986589970',
      numeroVo: '897',
      bairroVo: 'MeuBairro897',
      cidadeVo: 'Rio de Janeiro',
      ufVo: 'RJ',
      complementoVo: 'RJ',
      CEPVo: 'RJ',
      instituicao: 'Igreja',
      nomeIg: 'Primeira Igreja Batista em Torinho Branco',
      telefoneIg: '(21) 4358-9621',
      cepIg: '23093-002',
      logradouroIg: 'Rua da pedras brilhantes',
      numeroIg: '898',
      bairroIg: '898',
      cidadeIg: 'Rio de Janeiro',
      complementoIg: 'Rio de Janeiro',
      ufIg: 'RJ',
      pastor: 'João Batista de Jesus',
      telefonePa: '(21) 98563-1045',
      cepPa: '23094-002',
      logradouroPa: 'Rua da pedras amarelas',
      numeroPa: '899',
      cidadePa: 'Rio de Janeiro',
      bairroPa: 'Rio de Janeiro',
      complementoPa: 'Rio de Janeiro',
      ufPa: 'RJ',
      servicoOferecido: 'disicpulador',
      disponibilidade: 'Aos sábados',
      assiduidade: 'Aos sábados',
      diponivel: true,
      outrasInformacoes:
        'setá disponivel para participar do congresso radical, pretende fazer parte do programa de vontariado',
      email: 'dikaSilva@gmail.com',
      imgUrl: './assets/volu7.jpeg',
      dataCad: 'seg,25 de mai, 2020',
      status: VoluntaryStatus.ACTIVE,
    },
    {
      id: 8,
      nome: 'Larissa Maier Costa ',
      sexo: 'Feminino',
      dataNascimento: '1995-06-19',
      profissao: 'estudante',
      cepVo: '23092-002',
      logradouroVo: 'Rua da pedras cinzentas',
      telefoneVo: '(21) 986589970',
      numeroVo: '897',
      bairroVo: 'MeuBairro897',
      cidadeVo: 'Rio de Janeiro',
      ufVo: 'RJ',
      complementoVo: 'RJ',
      CEPVo: 'RJ',
      instituicao: 'Igreja',
      nomeIg: 'Primeira Igreja Batista em Torinho Branco',
      telefoneIg: '(21) 4358-9621',
      cepIg: '23093-002',
      logradouroIg: 'Rua da pedras brilhantes',
      numeroIg: '898',
      bairroIg: '898',
      cidadeIg: 'Rio de Janeiro',
      complementoIg: 'Rio de Janeiro',
      ufIg: 'RJ',
      pastor: 'João Batista de Jesus',
      telefonePa: '(21) 98563-1045',
      cepPa: '23094-002',
      logradouroPa: 'Rua da pedras amarelas',
      numeroPa: '899',
      cidadePa: 'Rio de Janeiro',
      bairroPa: 'Rio de Janeiro',
      complementoPa: 'Rio de Janeiro',
      ufPa: 'RJ',
      servicoOferecido: 'disicpulador',
      disponibilidade: 'Aos sábados',
      assiduidade: 'Aos sábados',
      diponivel: true,
      outrasInformacoes:
        'setá disponivel para participar do congresso radical, pretende fazer parte do programa de vontariado',
      email: 'dikaSilva@gmail.com',
      imgUrl: './assets/volu8.jpeg',
      dataCad: 'seg,25 de mai, 2020',
      status: VoluntaryStatus.ACTIVE,
    },
    {
      id: 9,
      nome: 'Thiago Nunes Botelho',
      sexo: 'M',
      dataNascimento: '1992-06-26',
      profissao: 'estudante',
      cepVo: '23092-002',
      logradouroVo: 'Rua da pedras cinzentas',
      numeroVo: '897',
      bairroVo: 'MeuBairro897',
      cidadeVo: 'Rio de Janeiro',
      ufVo: 'RJ',
      complementoVo: 'RJ',
      CEPVo: 'RJ',
      instituicao: 'Igreja',
      nomeIg: 'Primeira Igreja Batista em Torinho Branco',
      telefoneIg: '(21) 4358-9621',
      cepIg: '23093-002',
      logradouroIg: 'Rua da pedras brilhantes',
      numeroIg: '898',
      bairroIg: '898',
      cidadeIg: 'Rio de Janeiro',
      complementoIg: 'Rio de Janeiro',
      ufIg: 'RJ',
      pastor: 'João Batista de Jesus',
      telefonePa: '(21) 98563-1045',
      cepPa: '23094-002',
      logradouroPa: 'Rua da pedras amarelas',
      numeroPa: '899',
      cidadePa: 'Rio de Janeiro',
      bairroPa: 'Rio de Janeiro',
      complementoPa: 'Rio de Janeiro',
      ufPa: 'RJ',
      servicoOferecido: 'disicpulador',
      disponibilidade: 'Aos sábados',
      assiduidade: 'Aos sábados',
      diponivel: true,
      outrasInformacoes:
        'setá disponivel para participar do congresso radical, pretende fazer parte do programa de vontariado',
      email: 'dikaSilva@gmail.com',
      telefoneVo: '(21) 986589970',
      imgUrl: './assets/volu9.jpeg',
      dataCad: null,
      status: VoluntaryStatus.ACTIVE,
    },
    {
      id: 10,
      nome: 'José Antônio Gonçalves ',
      sexo: 'M',
      dataNascimento: '1995-06-19',
      profissao: 'Professor',
      cepVo: null,
      logradouroVo: null,
      numeroVo: '34',
      bairroVo: 'São Basílio',
      cidadeVo: 'Rio de Janeiro',
      ufVo: 'RJ',
      complementoVo: 'casa',
      CEPVo: '21270080',
      instituicao: 'igreja',
      nomeIg: 'Igreja Batista do Parque são Basílio',
      telefoneIg: '24150017',
      cepIg: '21270080',
      logradouroIg: null,
      numeroIg: '1716',
      bairroIg: 'campo grande',
      cidadeIg: 'Rio de janeiro',
      complementoIg: null,
      ufIg: 'RJ',
      pastor: 'Waldemir alves da silva',
      telefonePa: '24150017',
      cepPa: '6516516',
      logradouroPa: null,
      numeroPa: '1716',
      cidadePa: 'Rio de janeiro',
      bairroPa: ' campo grande ',
      complementoPa: 'dfdsa',
      ufPa: 'RJ',
      servicoOferecido: 'Aulas de Portugues ',
      disponibilidade: 'sabado',
      assiduidade: 'terca',
      diponivel: null,
      outrasInformacoes: 'Disponível também para discipualdo e alfabetização',
      email: 'antoniog@yahoo.com.br',
      telefoneVo: '21988756946',
      imgUrl: 'C:\\fakepath\\WhatsApp Image 2019-03-11 at 20.02.21.jpeg',
      dataCad: null,
      status: VoluntaryStatus.ACTIVE,
    },
    {
      id: 11,
      nome: 'bruno medeiros cabral',
      sexo: 'M',
      dataNascimento: '1992-06-11',
      profissao: 'programador',
      cepVo: null,
      logradouroVo: 'Zaira de oliveira ',
      numeroVo: '278',
      bairroVo: 'campo grande',
      cidadeVo: 'Rio de Janeiro',
      ufVo: 'RJ',
      complementoVo: 'casa',
      CEPVo: '21270080',
      instituicao: 'igreja',
      nomeIg: 'primeira igreja batista de espigão do oeste',
      telefoneIg: '34815696',
      cepIg: '789856356',
      logradouroIg: null,
      numeroIg: '8555',
      bairroIg: 'morada do sol',
      cidadeIg: 'Espigão do oeste',
      complementoIg: 'predio',
      ufIg: null,
      pastor: 'João Batista de Jesus',
      telefonePa: '69856336558',
      cepPa: '859965',
      logradouroPa: null,
      numeroPa: '897',
      cidadePa: 'Rio de Janeiro',
      bairroPa: 'MeuBairro897',
      complementoPa: 'asdfadfa',
      ufPa: 'RN',
      servicoOferecido: 'discipulador',
      disponibilidade: 'sabado',
      assiduidade: 'umaVezPorSemana',
      diponivel: null,
      outrasInformacoes:
        'desejo ajudar como programador auxiliando na automação das instituições',
      email: 'chanpion1300@gmail.com',
      telefoneVo: '988734469',
      imgUrl: './assets/bruno.jpg',
      dataCad: null,
      status: VoluntaryStatus.ACTIVE,
    },
    {
      id: 12,
      nome: 'Joana Patricia Oliveira',
      sexo: 'F',
      dataNascimento: '1992-06-11',
      profissao: 'programadora',
      cepVo: null,
      logradouroVo: 'Zariraa de oilive ',
      numeroVo: '278',
      bairroVo: 'campo grande',
      cidadeVo: 'Rio de Janeiro',
      ufVo: 'RJ',
      complementoVo: 'casa',
      CEPVo: '21270080',
      instituicao: 'igreja',
      nomeIg: 'primeira igreja batista de espigão do oeste',
      telefoneIg: '34815696',
      cepIg: '789856356',
      logradouroIg: null,
      numeroIg: '8555',
      bairroIg: 'morada do sol',
      cidadeIg: 'Espigão do oeste',
      complementoIg: 'predio',
      ufIg: null,
      pastor: 'João Batista de Jesus',
      telefonePa: '69856336558',
      cepPa: '859965',
      logradouroPa: null,
      numeroPa: '897',
      cidadePa: 'Rio de Janeiro',
      bairroPa: 'MeuBairro897',
      complementoPa: 'asdfadfa',
      ufPa: 'RN',
      servicoOferecido: 'discipulador',
      disponibilidade: 'sabado',
      assiduidade: 'umaVezPorSemana',
      diponivel: null,
      outrasInformacoes:
        'desejo ajudar como programador auxiliando na automação das instituições',
      email: 'chanpion1300@gmail.com',
      telefoneVo: '988734469',
      imgUrl: './assets/volu13.jpg',
      dataCad: null,
      status: VoluntaryStatus.ACTIVE,
    },
  ];

  getAll() {
    return this.VOLUNTEERS;
  }
  getById(id: number) {
    // tslint:disable-next-line: triple-equals
    const voluntary = this.VOLUNTEERS.find((value) => value.id == id);
    return voluntary;
  }

  create(voluntary: VoluntaryModelB) {
    let lastId = 0;
    if (this.VOLUNTEERS.length > 0) {
      lastId = this.VOLUNTEERS[this.VOLUNTEERS.length - 1].id;
    }
    voluntary.id = lastId + 1;
    this.VOLUNTEERS.push(voluntary);
    return voluntary;
  }

  update(voluntary: VoluntaryModelB) {
    const voluntaryArray = this.getById(voluntary.id);
    if (voluntaryArray) {
      voluntaryArray.id = voluntary.id;
      voluntaryArray.nome = voluntary.nome;
      voluntaryArray.sexo = voluntary.sexo;
      voluntaryArray.dataNascimento = voluntary.dataNascimento;
      voluntaryArray.profissao = voluntary.profissao;
      voluntaryArray.cepVo = voluntary.cepVo;
      voluntaryArray.logradouroVo = voluntary.logradouroVo;
      voluntaryArray.telefoneVo = voluntary.telefoneVo;
      voluntaryArray.numeroVo = voluntary.numeroVo;
      voluntaryArray.bairroVo = voluntary.bairroVo;
      voluntaryArray.cidadeVo = voluntary.cidadeVo;
      voluntaryArray.ufVo = voluntary.ufVo;
      voluntaryArray.complementoVo = voluntary.complementoVo;
      voluntaryArray.CEPVo = voluntary.CEPVo;
      voluntaryArray.instituicao = voluntary.instituicao;
      voluntaryArray.nomeIg = voluntary.nomeIg;
      voluntaryArray.telefoneIg = voluntary.telefoneIg;
      voluntaryArray.cepIg = voluntary.cepIg;
      voluntaryArray.logradouroIg = voluntary.logradouroIg;
      voluntaryArray.numeroIg = voluntary.numeroIg;
      voluntaryArray.bairroIg = voluntary.bairroIg;
      voluntaryArray.cidadeIg = voluntary.cidadeIg;
      voluntaryArray.complementoIg = voluntary.complementoIg;
      voluntaryArray.ufIg = voluntary.ufIg;
      voluntaryArray.pastor = voluntary.pastor;
      voluntaryArray.telefonePa = voluntary.telefonePa;
      voluntaryArray.cepPa = voluntary.cepPa;
      voluntaryArray.logradouroPa = voluntary.logradouroPa;
      voluntaryArray.numeroPa = voluntary.numeroPa;
      voluntaryArray.cidadePa = voluntary.cidadePa;
      voluntaryArray.bairroPa = voluntary.bairroPa;
      voluntaryArray.complementoPa = voluntary.complementoPa;
      voluntaryArray.ufPa = voluntary.ufPa;
      voluntaryArray.servicoOferecido = voluntary.servicoOferecido;
      voluntaryArray.disponibilidade = voluntary.disponibilidade;
      voluntaryArray.assiduidade = voluntary.assiduidade;
      voluntaryArray.diponivel = voluntary.diponivel;
      voluntaryArray.outrasInformacoes = voluntary.outrasInformacoes;
      voluntaryArray.email = voluntary.email;
      voluntaryArray.imgUrl = voluntary.imgUrl;
      voluntaryArray.dataCad = voluntary.dataCad;
      voluntaryArray.status = voluntary.status;
    } else {
      return voluntaryArray;
    }
  }

  delete(id: number) {
    const index = this.VOLUNTEERS.findIndex((item) => item.id === id);
    this.VOLUNTEERS.splice(index, 1);
  }
}
