import { Voluntary } from './../shared/voluntary';
import { Injectable } from '@nestjs/common';
import { VoluntaryModel } from 'libs/data/src/lib/data';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';

@Injectable()
export class VolunteersService {
  constructor(
    @InjectModel('Voluntary') private readonly voluntaryModel: Model<Voluntary>
  ) {}

  // VOLUNTEERS: VoluntaryModel[] = [
  //   {
  //     _id: "1",
    //   nome: 'Adriana da Silva Meluieer Bragança',
    //   sexo: 'Feminino',
    //   dataNascimento: '1995-06-19',
    //   profissao: 'estudante',
    //   endereco: {
    //     CEP: '23092-002',
    //     rua: 'Rua da pedras cinzentas',
    //     numero: '897',
    //     bairro: 'MeuBairro897',
    //     cidade: 'Rio de Janeiro',
    //     uf: 'RJ',
    //     complemento: 'RJ',
    //   },
    //   nomeIg: 'Primeira Igreja Batista em Torinho Branco',
    //   pastor: 'João Batista de Jesus',
    //   servicoOferecido: 'disicpulador',
    //   email: 'dikaSilva@gmail.com',
    //   telefone: '(21) 986589970',
    //   telefoneFx: '2134568569',
    //   imgUrlPrincipal: './assets/volu2.jpeg',
    //   chekbox1Profissao: false,
    //   chekbox2Intercessor: true,
    //   chekbox3Cuidador: true,
    //   chekbox4: true,
    //   chekbox5Aconselhamento: true,
    //   especialidade: 'piscicologo',
    //   imagesDocUrl: {
    //     imgRG: './assets/docs/docTeste',
    //     imgCPF: './assets/docs/docTeste',
    //     imgComprovResidencia: './assets/docs/docTeste',
    //     imgCartaIgreja: './assets/docs/docTeste',
    //   },
    //   dataCad: null,
    //   status: VoluntaryStatus.ACTIVE,
    // },
  //   {
  //     _id: "4",
  //     nome: 'Bruna Medeiros ',
  //     sexo: 'F',
  //     dataNascimento: '1995-06-21',
  //     profissao: 'cabelereira',
  //     endereco: {
  //       CEP: '21458965',
  //       rua: 'Rua Novo Oeste',
  //       numero: '2823',
  //       bairro: 'MeuBairro2823',
  //       cidade: 'São Paulo',
  //       uf: 'SP',
  //       complemento: 'SP',
  //     },
  //     nomeIg: 'Primeira Igreja Batista em SP',
  //     pastor: 'MArco Aurélio Silva',
  //     servicoOferecido: 'Cabelereira',
  //     email: 'brunamedeiros@gmail.com',
  //     telefone: '(11) 965874521',
  //     telefoneFx: '2134568569',
  //     imgUrlPrincipal: './assets/volu4.jpeg',
  //     chekbox1Profissao: true,
  //     chekbox2Intercessor: true,
  //     chekbox3Cuidador: true,
  //     chekbox4: true,
  //     chekbox5Aconselhamento: true,
  //     especialidade: 'piscicologo',
  //     imagesDocUrl: {
  //       imgRG: './assets/docs/docTeste',
  //       imgCPF: './assets/docs/docTeste',
  //       imgComprovResidencia: './assets/docs/docTeste',
  //       imgCartaIgreja: './assets/docs/docTeste',
  //     },
  //     dataCad: null,
  //     status: VoluntaryStatus.ACTIVE,
  //   },
  //   {
  //     _id: "5",
  //     nome: 'Alessandro Vieira Fernandes ',
  //     sexo: 'Masculino',
  //     dataNascimento: '1995-06-19',
  //     profissao: 'estudante',
  //     endereco: {
  //       CEP: '23092-002',
  //       rua: 'Rua da pedras cinzentas',
  //       numero: '897',
  //       bairro: 'MeuBairro897',
  //       cidade: 'Rio de Janeiro',
  //       uf: 'RJ',
  //       complemento: 'RJ',
  //     },
  //     telefone: '(21) 986589970',
  //     telefoneFx: '2134568569',
  //     nomeIg: 'Primeira Igreja Batista em Torinho Branco',
  //     pastor: 'João Batista de Jesus',
  //     servicoOferecido: 'disicpulador',
  //     email: 'dikaSilva@gmail.com',
  //     imgUrlPrincipal: './assets/volu3.jpeg',
  //     chekbox1Profissao: true,
  //     chekbox2Intercessor: true,
  //     chekbox3Cuidador: true,
  //     chekbox4: true,
  //     chekbox5Aconselhamento: true,
  //     especialidade: 'piscicologo',
  //     imagesDocUrl: {
  //       imgRG: './assets/docs/docTeste',
  //       imgCPF: './assets/docs/docTeste',
  //       imgComprovResidencia: './assets/docs/docTeste',
  //       imgCartaIgreja: './assets/docs/docTeste',
  //     },
  //     dataCad: 'seg,25 de mai, 2020',
  //     status: VoluntaryStatus.ACTIVE,
  //   },
  //   {
  //     _id: "6",
  //     nome: 'Sônia Gonsalves da Silva ',
  //     sexo: 'Feminino',
  //     dataNascimento: '1995-06-19',
  //     profissao: 'estudante',
  //     endereco: {
  //       CEP: '23092-002',
  //       rua: 'Rua da pedras cinzentas',
  //       numero: '897',
  //       bairro: 'MeuBairro897',
  //       cidade: 'Rio de Janeiro',
  //       uf: 'RJ',
  //       complemento: 'RJ',
  //     },
  //     telefone: '(21) 986589970',
  //     telefoneFx: '2134568569',
  //     nomeIg: 'Primeira Igreja Batista em Torinho Branco',
  //     pastor: 'João Batista de Jesus',
  //     servicoOferecido: 'disicpulador',
  //     email: 'dikaSilva@gmail.com',
  //     imgUrlPrincipal: './assets/volu6.jpeg',
  //     chekbox1Profissao: true,
  //     chekbox2Intercessor: true,
  //     chekbox3Cuidador: true,
  //     chekbox4: true,
  //     chekbox5Aconselhamento: true,
  //     especialidade: 'piscicologo',
  //     imagesDocUrl: {
  //       imgRG: './assets/docs/docTeste',
  //       imgCPF: './assets/docs/docTeste',
  //       imgComprovResidencia: './assets/docs/docTeste',
  //       imgCartaIgreja: './assets/docs/docTeste',
  //     },
  //     dataCad: 'seg,25 de mai, 2020',
  //     status: VoluntaryStatus.ACTIVE,
  //   },
  //   {
  //     _id: "7",
  //     nome: 'Thayse Alvez Romanu ',
  //     sexo: 'Feminino',
  //     dataNascimento: '1995-06-19',
  //     profissao: 'estudante',
  //     endereco: {
  //       CEP: '23092-002',
  //       rua: 'Rua da pedras cinzentas',
  //       numero: '897',
  //       bairro: 'MeuBairro897',
  //       cidade: 'Rio de Janeiro',
  //       uf: 'RJ',
  //       complemento: 'RJ',
  //     },
  //     telefone: '(21) 986589970',
  //     telefoneFx: '2134568569',
  //     nomeIg: 'Primeira Igreja Batista em Torinho Branco',
  //     pastor: 'João Batista de Jesus',
  //     servicoOferecido: 'disicpulador',
  //     email: 'dikaSilva@gmail.com',
  //     imgUrlPrincipal: './assets/volu7.jpeg',
  //     chekbox1Profissao: true,
  //     chekbox2Intercessor: true,
  //     chekbox3Cuidador: true,
  //     chekbox4: true,
  //     chekbox5Aconselhamento: true,
  //     especialidade: 'piscicologo',
  //     imagesDocUrl: {
  //       imgRG: './assets/docs/docTeste',
  //       imgCPF: './assets/docs/docTeste',
  //       imgComprovResidencia: './assets/docs/docTeste',
  //       imgCartaIgreja: './assets/docs/docTeste',
  //     },
  //     dataCad: 'seg,25 de mai, 2020',
  //     status: VoluntaryStatus.ACTIVE,
  //   },
  //   {
  //     _id: "8",
  //     nome: 'Larissa Maier Costa ',
  //     sexo: 'Feminino',
  //     dataNascimento: '1995-06-19',
  //     profissao: 'estudante',
  //     endereco: {
  //       CEP: '23092-002',
  //       rua: 'Rua da pedras cinzentas',
  //       numero: '897',
  //       bairro: 'MeuBairro897',
  //       cidade: 'Rio de Janeiro',
  //       uf: 'RJ',
  //       complemento: 'RJ',
  //     },
  //     telefone: '(21) 986589970',
  //     telefoneFx: '2134568569',
  //     nomeIg: 'Primeira Igreja Batista em Torinho Branco',
  //     pastor: 'João Batista de Jesus',
  //     servicoOferecido: 'disicpulador',
  //     email: 'dikaSilva@gmail.com',
  //     imgUrlPrincipal: './assets/volu8.jpeg',
  //     chekbox1Profissao: true,
  //     chekbox2Intercessor: true,
  //     chekbox3Cuidador: true,
  //     chekbox4: true,
  //     chekbox5Aconselhamento: true,
  //     especialidade: 'piscicologo',
  //     imagesDocUrl: {
  //       imgRG: './assets/docs/docTeste',
  //       imgCPF: './assets/docs/docTeste',
  //       imgComprovResidencia: './assets/docs/docTeste',
  //       imgCartaIgreja: './assets/docs/docTeste',
  //     },
  //     dataCad: 'seg,25 de mai, 2020',
  //     status: VoluntaryStatus.ACTIVE,
  //   },
  //   {
  //     _id: "9",
  //     nome: 'Thiago Nunes Botelho',
  //     sexo: 'M',
  //     dataNascimento: '1992-06-26',
  //     profissao: 'estudante',
  //     endereco: {
  //       CEP: '23092-002',
  //       rua: 'Rua da pedras cinzentas',
  //       numero: '897',
  //       bairro: 'MeuBairro897',
  //       cidade: 'Rio de Janeiro',
  //       uf: 'RJ',
  //       complemento: 'RJ',
  //     },
  //     nomeIg: 'Primeira Igreja Batista em Torinho Branco',
  //     pastor: 'João Batista de Jesus',
  //     servicoOferecido: 'disicpulador',
  //     email: 'dikaSilva@gmail.com',
  //     telefone: '(21) 986589970',
  //     telefoneFx: '2134568569',
  //     imgUrlPrincipal: './assets/volu9.jpeg',
  //     chekbox1Profissao: true,
  //     chekbox2Intercessor: true,
  //     chekbox3Cuidador: true,
  //     chekbox4: true,
  //     chekbox5Aconselhamento: true,
  //     especialidade: 'piscicologo',
  //     imagesDocUrl: {
  //       imgRG: './assets/docs/docTeste',
  //       imgCPF: './assets/docs/docTeste',
  //       imgComprovResidencia: './assets/docs/docTeste',
  //       imgCartaIgreja: './assets/docs/docTeste',
  //     },
  //     dataCad: null,
  //     status: VoluntaryStatus.ACTIVE,
  //   },
  //   {
  //     _id: "10",
  //     nome: 'José Antônio Gonçalves ',
  //     sexo: 'M',
  //     dataNascimento: '1995-06-19',
  //     profissao: 'Professor',
  //     endereco: {
  //       rua: null,
  //       numero: '34',
  //       bairro: 'São Basílio',
  //       cidade: 'Rio de Janeiro',
  //       CEP: '21270080',
  //       uf: 'RJ',
  //       complemento: 'casa',
  //     },

  //     nomeIg: 'Igreja Batista do Parque são Basílio',
  //     pastor: 'Waldemir alves da silva',
  //     servicoOferecido: 'Aulas de Portugues ',
  //     email: 'antoniog@yahoo.com.br',
  //     telefone: '21988756946',
  //     telefoneFx: '2134568569',
  //     imgUrlPrincipal: './assets/volu9.jpeg',
  //     chekbox1Profissao: false,
  //     chekbox2Intercessor: false,
  //     chekbox3Cuidador: false,
  //     chekbox4: false,
  //     chekbox5Aconselhamento: true,
  //     especialidade: 'piscicologo',
  //     imagesDocUrl: {
  //       imgRG: './assets/docs/docTeste',
  //       imgCPF: './assets/docs/docTeste',
  //       imgComprovResidencia: './assets/docs/docTeste',
  //       imgCartaIgreja: './assets/docs/docTeste',
  //     },
  //     dataCad: null,
  //     status: VoluntaryStatus.ACTIVE,
  //   },
  //   {
  //     _id: "11",
  //     nome: 'bruno medeiros cabral',
  //     sexo: 'M',
  //     dataNascimento: '1992-06-11',
  //     profissao: 'programador',
  //     endereco: {
  //       rua: 'Zaira de oliveira ',
  //       numero: '278',
  //       bairro: 'campo grande',
  //       cidade: 'Rio de Janeiro',
  //       uf: 'RJ',
  //       complemento: 'casa',
  //       CEP: '21270080',
  //     },
  //     nomeIg: 'primeira igreja batista de espigão do oeste',
  //     pastor: 'João Batista de Jesus',
  //     servicoOferecido: 'discipulador',
  //     email: 'chanpion1300@gmail.com',
  //     telefone: '988734469',
  //     telefoneFx: '2134568569',
  //     imgUrlPrincipal: './assets/bruno.jpg',
  //     chekbox1Profissao: true,
  //     chekbox2Intercessor: true,
  //     chekbox3Cuidador: true,
  //     chekbox4: true,
  //     chekbox5Aconselhamento: true,
  //     especialidade: 'piscicologo',
  //     imagesDocUrl: {
  //       imgRG: './assets/docs/docTeste',
  //       imgCPF: './assets/docs/docTeste',
  //       imgComprovResidencia: './assets/docs/docTeste',
  //       imgCartaIgreja: './assets/docs/docTeste',
  //     },
  //     dataCad: null,
  //     status: VoluntaryStatus.ACTIVE,
  //   },
  // ];
 
  async getAll() {
    return await this.voluntaryModel.find().exec();
  }
  async getById(id: string) {
    return await this.voluntaryModel.findById(id).exec();
  }

  async create(voluntary: Voluntary) {
    const createdVoluntary = new this.voluntaryModel(voluntary);
    return await createdVoluntary.save();
  }

  async update(id: string, voluntary: Voluntary) {
    await this.voluntaryModel.updateOne({ _id: id }, voluntary).exec();
    return this.getById(id);
  }

  async delete(id: string) {
    return await this.voluntaryModel.deleteOne({ _id: id }).exec()
  }

  findName(termo: string) {
   
  }
}
